### ISSUE TITLE
Refatorar para que possamos usar um mesmo consumer para ler de múltiplas filas

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/easyqueue#20]
Atualmente um consumer lê apenas de uma fila, mas não há impedimentos para que ele possa ler de múltiplas filas.

O que estamos fazendo aqui é basicamente fazer com que o método `on_queue_message()` do Delegate receba, junto com a mensagem, o nome da fila de onde ela veio. Esse é o ponto mais importante, mas esse método também receberá mais outras coisas, como `channel`, `properties` (AMQP) e etc.

```python
async def on_queue_message(self, message: AMQPMessage):
  pass
```

As definições de `AMQPMessage` e `AMQPConnection` estão aqui na discussão da issue: https://github.com/B2W-BIT/easyqueue/issues/20#issuecomment-452347891

**Comment by daltonmatos** [comment]
Acho que podemos ir no caminho de mudar a assinatura para receber apenas um objeto "envelope" que vai conter todas as informaçoes sobre a mensagem que está sendo entregue.

Conterá coisas como:

* Corpo da mensagem, já parseado, caso estejamos em uma `BaseJsonQueue`;
* AMQP Channel de onde dessa mensagem veio;
* Nome da fila de onde essa mensagem foi lida;
* AMQP Connection usada para falar como o broker;
* Delivery tag da mensagen;
* Atributos "low-level" do AMQP como "properties", "headers", etc.

@diogommartins

**Comment by daltonmatos** [comment]
Tivemos a ideia de dividir o objeto `BaseQueue` em dois:

* `BaseQueue`
* `AmqpConnection`

Assim poderemos ter responsabilidades específicas e já estaremos no caminho de poder ter múltiplas conexões em uma mesma instância de `Queue`, o que vai nos ajudar também podermos termos múltiplos consumers.

Temos que definir qual será o "contrato" que o objeto Queue deverá expor, penso em:

```python
class Queue(BaseQueue):

    def __init__(self, connections: List[AmqpConnection]):
        self.connections = AmqpConnections

    async def put(self, routing_key, connection_name:str, data = None, serialized_data = "", exchange = "", virtual_host:str = None):
        pass

    async def consume(self, queue_name, consumer_delegate: AsyncQueueConsumerDelegate, connection_name: str, virtual_host:str = None):
        pass

    async def ack(self, message: AmqpMessage):
        message.ack()

    async def reject(sef, message: AmqpMessage, requeue=True):
        message.reject(requeue=requeue)
```

# Observações

Como o  `Queue` recebe uma lista de conexões, que podem inclusive serem para brokers diferentes, temos que identificar qual conexão queremos usar no momento de fazer `put/consume`. Isso pode ser feito através de um nome único para a conexão.

Nos dois métodos onde recebemos `virtual_host`, caso ele seja `None` será usado o virtual host que foi passado no momento de instanciar uma `AmqpConnection`.

Vamos tentar fechar o contrato da `Queue` depois fechamos o da `AmqpConnection`.

@diogommartins  o que acha?

**Comment by diogommartins** [comment]
> Acho que podemos ir no caminho de mudar a assinatura para receber apenas um objeto "envelope" que vai conter todas as informaçoes sobre a mensagem que está sendo entregue.
> 
> Conterá coisas como:
> 
> * Corpo da mensagem, já parseado, caso estejamos em uma `BaseJsonQueue`;
> * AMQP Channel de onde dessa mensagem veio;
> * Nome da fila de onde essa mensagem foi lida;
> * AMQP Connection usada para falar como o broker;
> * Delivery tag da mensagen;
> * Atributos "low-level" do AMQP como "properties", "headers", etc.
> 
> @diogommartins

Concordo com tudo isso! Acho que esse é o caminho e podemos começar por aí =)

**Comment by diogommartins** [comment]
> Tivemos a ideia de dividir o objeto `BaseQueue` em dois:
> 
> * `BaseQueue`
> * `AmqpConnection`
> 
> Assim poderemos ter responsabilidades específicas e já estaremos no caminho de poder ter múltiplas conexões em uma mesma instância de `Queue`, o que vai nos ajudar também podermos termos múltiplos consumers.
> 
> Temos que definir qual será o "contrato" que o objeto Queue deverá expor, penso em:
> 
> ```python
> class Queue(BaseQueue):
> 
>     def __init__(self, connections: List[AmqpConnection]):
>         self.connections = AmqpConnections
> 
>     async def put(self, routing_key, connection_name:str, data = None, serialized_data = "", exchange = "", virtual_host:str = None):
>         pass

Ainda tenho que pensar um pouco pra amadurecer a ideia antes de ter uma opinião sobre `connection_name`. A ideia é que em apps como [async-worker](https://github.com/B2W-BIT/async-worker) a gente ainda consiga manter a interface pública como `put(data, routing_key, exchange)` ?

>     async def consume(self, queue_name, consumer_delegate: AsyncQueueConsumerDelegate, connection_name: str, virtual_host:str = None):
>         pass
> 
>     async def ack(self, message: AmqpMessage):
>         message.ack()

Aqui temos algum motivo especial para acoplar `ack` a AmqpMessage e não a `delivery tag` ? 

>     async def reject(sef, message: AmqpMessage, requeue=True):
>         message.reject(requeue=requeue)
> ```
> 
> # Observações
> Como o `Queue` recebe uma lista de conexões, que podem inclusive serem para brokers diferentes, temos que identificar qual conexão queremos usar no momento de fazer `put/consume`. Isso pode ser feito através de um nome único para a conexão.
> 
> Nos dois métodos onde recebemos `virtual_host`, caso ele seja `None` será usado o virtual host que foi passado no momento de instanciar uma `AmqpConnection`.
> 
> Vamos tentar fechar o contrato da `Queue` depois fechamos o da `AmqpConnection`.
> 
> @diogommartins o que acha?

**Comment by daltonmatos** [comment]
> Aqui temos algum motivo especial para acoplar `ack` a AmqpMessage e não a `delivery tag` ?

Penso mais no sentido de abstrair o `delivery_tag` mesmo. Para podermos pensar sempre em relação à mensagem como nossa abstração principal. Ela é o centro de tudo.

Assim quando queremos confirmar ou rejeitar, perguntamos pra ela. Ela, internamente, é que vai saber qual `AMQPChannel` usar e qual `delivery_tag`. 

A ideia de ter um método `ack()` na `Queue` é apenas uma conveniência. O `ack` pertence mesmo à mensagem.

Faz sentido?

**Comment by daltonmatos** [comment]
> Ainda tenho que pensar um pouco pra amadurecer a ideia antes de ter uma opinião sobre `connection_name`. 

Pois é, te entendo. Essa forma foi apenas uma que passou pela minha cabeça. Quando temos a possibilidade de ter múltiplas conexões que potencialmente podem ser para múltiplos brokers, temos que ter uma forma de dizer "com qual broker" queremos falar agora, afinal dois brokers podem ter configurações iguais: Uma fila/exchange/binding com mesmos nomes.

Aqui poderíamos até tentar fazer o objeto `Queue` ser sempre "mono-conexão", ou melhor, "mono-broker", ou seja, se conectar sempre com o mesmo broker. Assim para termos um worker que se conecta com múltiplos brokers teríamos múltiplas instâncias de `Queue`. Mas o problema seria essencialmente o mesmo, apenas em outra camada.

Teríamos novamente que saber decidir qual instância de `Queue` vamos querer usar. E aqui o `connection_name` apareceria novamente.

Mas pensando no `Queue` como sendo o "low-level building block" acho que ele ser "mono-broker" não é um problema.

Dessa forma quando asyncworker receber múltiplos objetos `AMQPConnection` ele vai ser responsável por gerenciar uma lista de instâncias de `Queue`. Assim o `handler` usaria o `connection_name` apenas para obter a instâncias correta de `Queue` e com essa instância em mãos poderia fazer: `await put(routing_key, data = None, serialized_data = "", exchange = "", virtual_host:str = None)`.

Aqui o asyncworker pode até fazer algumas validações, por exemplo:

* Se ele recebeu apenas uma Connection, o `name` não é obrigatório;
* Se recebeu mais de uma Connection, todas precisam ter `name` e os nomes devem ser distintos.

Indo por essa linha o construtor do `Queue` recebeia um parametro opcional chamado `name`.

Penso sempre na implementação de um shovel, que lê de um broker e escreve em outro(s). Esse é o pensamento que direciona minhas ideias sobre multi-conexão.

> A ideia é que em apps como [async-worker](https://github.com/B2W-BIT/async-worker) a gente ainda consiga manter a interface pública como `put(data, routing_key, exchange)` ?

Então, "sim" mas apenas para a conexão principal, ou seja, para a mesma conexão que está entregando mensagems para o handler, entende?

Pensa no seguinte:

```python

@app.route(["queue"], ...)
async def handler(m: List[RabbitMQMessage]):

    main_queue = app[RouteTypes.AMQP]['connection']
    ....
    ....
```

Aqui, `main_queue` é a conexão com o **mesmo** broker que está entregando mensagens para esse `handler`. Aqui o `put()` pode ser com essa assinatura que você falou, pois o broker escolhido já está implícito.

Se esse handler precisar usar a conexão com outro broker:

* Ou ele mesmo abre a conexão (durante o `init_app`). E aí ele vai ter múltiplas variáveis, cada uma contendo uma conexão com um broker diferente. Veja que aqui o nome dessa variáveis já é equivalente ao `connection_name`;
* Ou ele passa os dados de conexão para o asyncworker e o próprio asynworker abre a nova conexão.

Na segunda opção o asyncworker tem que dar uma forma de "selecionar" a conexão desejada.

O que acha?

**Comment by daltonmatos** [comment]
Outro ponto, importante.

O divisão de múltiplas conexões para um mesmo consumer pod estar implementada aqui. De alguma forma, ao construir uma instância de `Queue` já podemos falar quantas conexões queremos que ela use. Assim, internamente, quando chamarmos `await queue.consume()` as múltiplas conexões serão abertas e o `on_queue_message` será chamado recebendo mensagens de todas essas múltiplas conexões.

O que acha dessa abstração estar aqui?

**Comment by diogommartins** [comment]
> A ideia de ter um método `ack()` na `Queue` é apenas uma conveniência. O `ack` pertence mesmo à mensagem.



> > Aqui temos algum motivo especial para acoplar `ack` a AmqpMessage e não a `delivery tag` ?
> 
> Penso mais no sentido de abstrair o `delivery_tag` mesmo. Para podermos pensar sempre em relação à mensagem como nossa abstração principal. Ela é o centro de tudo.
> 
> Assim quando queremos confirmar ou rejeitar, perguntamos pra ela. Ela, internamente, é que vai saber qual `AMQPChannel` usar e qual `delivery_tag`.

Entendi a ideia e concordo com a mudança de interface


> A ideia de ter um método `ack()` na `Queue` é apenas uma conveniência. O `ack` pertence mesmo à mensagem.
> 
> Faz sentido?

Considerando que a ação é "o canal confirma a mensagem" e não "mensagem confirma canal" ou "mensagem se confirma no canal", o canal é o ator da ação e dono do método. Acho que a inversão de controle não cabe aqui

**Comment by daltonmatos** [comment]
> Considerando que a ação é "o canal confirma a mensagem" e não "mensagem confirma canal" ou "mensagem se confirma no canal", o canal é o ator da ação e dono do método. Acho que a inversão de controle não cabe aqui

Concordo. Podemos então fazer assim:

```python

async def ack(self, m: RabbitMQMessage):
  self.conn._channel.basic_ack(m.delivery_tag)

```

:+1: ?

**Comment by diogommartins** [comment]
> Indo por essa linha o construtor do `Queue` recebeia um parametro opcional chamado `name`.



> > Ainda tenho que pensar um pouco pra amadurecer a ideia antes de ter uma opinião sobre `connection_name`.
> 
> Pois é, te entendo. Essa forma foi apenas uma que passou pela minha cabeça. Quando temos a possibilidade de ter múltiplas conexões que potencialmente podem ser para múltiplos brokers, temos que ter uma forma de dizer "com qual broker" queremos falar agora, afinal dois brokers podem ter configurações iguais: Uma fila/exchange/binding com mesmos nomes.
> 
> Aqui poderíamos até tentar fazer o objeto `Queue` ser sempre "mono-conexão", ou melhor, "mono-broker", ou seja, se conectar sempre com o mesmo broker. Assim para termos um worker que se conecta com múltiplos brokers teríamos múltiplas instâncias de `Queue`. Mas o problema seria essencialmente o mesmo, apenas em outra camada.
> 
> Teríamos novamente que saber decidir qual instância de `Queue` vamos querer usar. E aqui o `connection_name` apareceria novamente.
> 
> Mas pensando no `Queue` como sendo o "low-level building block" acho que ele ser "mono-broker" não é um problema.
> 
> Dessa forma quando asyncworker receber múltiplos objetos `AMQPConnection` ele vai ser responsável por gerenciar uma lista de instâncias de `Queue`. Assim o `handler` usaria o `connection_name` apenas para obter a instâncias correta de `Queue` e com essa instância em mãos poderia fazer: `await put(routing_key, data = None, serialized_data = "", exchange = "", virtual_host:str = None)`.
> 
> Aqui o asyncworker pode até fazer algumas validações, por exemplo:
> 
> * Se ele recebeu apenas uma Connection, o `name` não é obrigatório;
> * Se recebeu mais de uma Connection, todas precisam ter `name` e os nomes devem ser distintos.
> 
> Indo por essa linha o construtor do `Queue` recebeia um parametro opcional chamado `name`.

Acho que só é relevante ter `name` no nível do async-worker

> Penso sempre na implementação de um shovel, que lê de um broker e escreve em outro(s). Esse é o pensamento que direciona minhas ideias sobre multi-conexão.
> 
> > A ideia é que em apps como [async-worker](https://github.com/B2W-BIT/async-worker) a gente ainda consiga manter a interface pública como `put(data, routing_key, exchange)` ?
> 
> Então, "sim" mas apenas para a conexão principal, ou seja, para a mesma conexão que está entregando mensagems para o handler, entende?
> 
> Pensa no seguinte:
> 
> ```python
> @app.route(["queue"], ...)
> async def handler(m: List[RabbitMQMessage]):
> 
>     main_queue = app[RouteTypes.AMQP]['connection']
>     ....
>     ....
> ```
> 
> Aqui, `main_queue` é a conexão com o **mesmo** broker que está entregando mensagens para esse `handler`. Aqui o `put()` pode ser com essa assinatura que você falou, pois o broker escolhido já está implícito.
> 
> Se esse handler precisar usar a conexão com outro broker:
> 
> * Ou ele mesmo abre a conexão (durante o `init_app`). E aí ele vai ter múltiplas variáveis, cada uma contendo uma conexão com um broker diferente. Veja que aqui o nome dessa variáveis já é equivalente ao `connection_name`;
> * Ou ele passa os dados de conexão para o asyncworker e o próprio asynworker abre a nova conexão.
> 
> Na segunda opção o asyncworker tem que dar uma forma de "selecionar" a conexão desejada.
> 
> O que acha?

Faz sentido. Entendi que conseguimos manter a mesma interface pública adicionando features como um `app.get_connection(name: str): ...`, etc

**Comment by daltonmatos** [comment]
> Acho que só é relevante ter `name` no nível do async-worker

Concordo. :tada:

**Comment by daltonmatos** [comment]
> Faz sentido. Entendi que conseguimos manter a mesma interface pública adicionando features como um `app.get_connection(name: str): ...`, etc

Sim. O nome do método até pode mudar. Acho que ainda vamos matura mais essa ideia e com o tempo teremos uma interface melhor.

**Comment by diogommartins** [comment]
Acho que podemos começar extraindo um domínio próprio pra conexão no easyqueue

``` python
class AMQPConnection:
    protocol: aioamqp.protocol.AmqpProtocol
    channel: asyncio.BaseTransport
    transport: aioamqp.channel.Channel

    host: str
    login: str
    password: str
    virtualhost: str
    loop: asyncio.AbstractEventLoop
    on_error: Callable
    heartbeat: int

    def is_connected(self) -> bool: ...
    async def close(self) -> None: ...
    async def _connect(self) -> None: ...
```

```python

class AMQPMessage:
    conn: AMQPConnection
```

E mudar as implementações para algo tipo:

```python
    @_ensure_connected
    async def ack(self, message: AMQMessage):
        return await msg.channel.basic_client_ack(msg.delivery_tag)
```

Até termos algo como `connections: List[AMQPConnection]` e podermos implementar um round-robin para operações paralelizáveis, como `put` e `consume`

**Comment by diogommartins** [comment]
Implementei AMQPMessage em 33acc5b . Não usei dataclasses pra manter a compatibilidade com py3.6

**Comment by diogommartins** [comment]
A refatoração para usar AMQPConnection já tá feita e já dá pra visualizar melhor como ficaria um pool de AMQPConnection 😃

**Comment by daltonmatos** [comment]
O https://github.com/B2W-BIT/easyqueue/pull/29 já é o caminho para podermos fazer esse pool.
