### ISSUE TITLE
Ter a possibilidade de passar um logger para o easyqueue

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/easyqueue#3]
Atualmente o easyqueue usa um logger próprio, e isso pode causar logs em formatos diferentes na mesma app, ex:

```
{"logged_at": "2018-06-07T10:47:17.569800", "line_number": 125, "function": "start", "level": "ERROR", "file_path": "/home/daltonmatos/sievegroup/sieve/asgard-counts-ingestor/worker/consumer.py", "type": "connection-failed", "dest": "127.0.0.1", "retry": true}
Server closed connection: NOT_ALLOWED - access to vhost 'fluentd_' refused for user 'fluentd', code=530, class_id=10, method_id=40
(530, "NOT_ALLOWED - access to vhost 'fluentd_' refused for user 'fluentd'")
Connection lost exc=None
(None, None)
{"logged_at": "2018-06-07T10:47:19.693126", "line_number": 125, "function": "start", "level": "ERROR", "file_path": "/home/daltonmatos/sievegroup/sieve/asgard-counts-ingestor/worker/consumer.py", "type": "connection-failed", "dest": "127.0.0.1", "retry": true}
```

passando um logger para o easyqueue ele poderia passar a usar o mesmo logger que app está usando.

**Comment by diogommartins** [comment]
Boa ! Vou ter que abrir essa issue lá no aioamqp primeiro, mas vale muito a pena

**Comment by daltonmatos** [comment]
@diogommartins o que acha de passarmos a usar, no easyqueue, os loggers com `name` definidos?

Dessa forma, código externos que desejam alterar esse logger podem fazer `loggin.getLogger("<name>")` para pegar uma instância desse log.

**Comment by diogommartins** [comment]
Já está na master, mas não sei qual PR fez isso pra poder referenciar :/
