### ISSUE TITLE
Remover a necessidade do delegate.queue_name

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/easyqueue#31]
No #29 fizemos uma grande refatoração que permite que uma mesma AsyncQueue possa consumir de múltiplas filas diferentes de forma concorrente.

Isso significa que podemos também reutilizar um ConsumerDelegate. Essa issue aqui é para removermos a necessidade do atributo `queue_name` do delegate. O nome da fila deve ser passado no momento de se iniciar um novo consumidor.

No proprio #29 tem algumas mensagens sugerindo o que fazer. Vou postá-las aqui também.

**Comment by daltonmatos** [comment]
A linha de pensamento dessa implementação seria ter um método `consume(queue_name: str)` no delegate. Esse método chamaria `self.queue.consume(queue_name)` e um novo consumidor seria iniciado.

Algo assim:

```python
class MyConsumer(AsyncQueueConsumerDelegate):
    
    def __init__(self):
        self.queue = AsyncJsonQueue(
            host='localhost',
            username='guest',
            password='guest',
            delegate=self
        )

    async def on_queue_message(self, msg: AMQPMessage[dict]):
        print(msg.deserialized_data)  # do something with
        await self.queue.ack(msg)  # dont forget to ack =)

   async def consume(queue_name: str):
        return self.queue.consume(queue_name)

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    consumer = MyConsumer()
    loop.create_task(consumer.consume("my-queue-name"))
    loop.run_forever()
```

Na verdade o métod `consume(queue_name: str)` poderia até pertencer ao `BaseDeleagate`. Talvez um problema seja que o Delegate não conhecer a `queue`. Então temos que pensar em um jeito de ao mesmo tempo não repetir o `consume()` em todos os delegates criados por aí e poder ter uma implementação do `consume()` que saiba em qual instancia de `queue` chamar o `consume()`.

Se construímos o delgate dessa forma acima, dependemos dele percisar de um `__init__()` que faz a inicialização de um `self.queue`.

Se criamos primeiro a instância de AsyncQueue, deixamos de precisar de um `consume()` no delegate, afinal poderemos chamar direto o `consume()` da `AsyncQueue`. Algo assim:

```python

class MyConsumer(AsyncQueueConsumerDelegate):

    async def on_queue_message(self, msg: AMQPMessage[dict]):
        print(msg.deserialized_data)  # do something with
        await self.queue.ack(msg)  # dont forget to ack =)

queue = AsyncJsonQueue(
            host='localhost',
            username='guest',
            password='guest',
            delegate=MyConsumer()
        )

consumer_tag = queue.consume("my-queue-name")
```

Aí fica a pergunta: E se o delegate **não for** um parametro do construtor da `AsyncQueue` e sim do método `consume(queue_name: str)`? Algo assim:

```python
class MyConsumer(AsyncQueueConsumerDelegate):

    async def on_queue_message(self, msg: AMQPMessage[dict]):
        print(msg.deserialized_data)  # do something with
        await self.queue.ack(msg)  # dont forget to ack =)

consumer_delegate = MyConsumer()

queue = AsyncJsonQueue(
            host='localhost',
            username='guest',
            password='guest'
        )

consumer_tag = queue.consume(queue_name="my-queue-name", delegate=consumer_delegate)
```

Faz sentido?

**Comment by diogommartins** [comment]
> ....
> Se criamos primeiro a instância de AsyncQueue, deixamos de precisar de um `consume()` no delegate, afinal poderemos chamar direto o `consume()` da `AsyncQueue`. Algo assim:
> 
> ```python
> class MyConsumer(AsyncQueueConsumerDelegate):
> 
>     async def on_queue_message(self, msg: AMQPMessage[dict]):
>         print(msg.deserialized_data)  # do something with
>         await self.queue.ack(msg)  # dont forget to ack =)
> 
> queue = AsyncJsonQueue(
>             host='localhost',
>             username='guest',
>             password='guest',
>             delegate=MyConsumer()
>         )
> 
> consumer_tag = queue.consume("my-queue-name")
> ```
> 
> Aí fica a pergunta: E se o delegate **não for** um parametro do construtor da `AsyncQueue` e sim do método `consume(queue_name: str)`? Algo assim:
> 
> ```python
> class MyConsumer(AsyncQueueConsumerDelegate):
> 
>     async def on_queue_message(self, msg: AMQPMessage[dict]):
>         print(msg.deserialized_data)  # do something with
>         await self.queue.ack(msg)  # dont forget to ack =)
> 
> consumer_delegate = MyConsumer()
> 
> queue = AsyncJsonQueue(
>             host='localhost',
>             username='guest',
>             password='guest'
>         )
> 
> consumer_tag = queue.consume(queue_name="my-queue-name", delegate=consumer_delegate)
> ```
> 
> Faz sentido?

Faz todos sentido, @daltonmatos ! Estou trabalhando numa implementação assim. Iluminou o caminho =)
