### ISSUE TITLE
Mudança no `on_queue_error()` para receber a Exception original

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/easyqueue#4]
Atualmente, o `on_queue_error()` passa, no parametro `error`, o resultado de `str(Exception)`.

Seria melhor passar a Exception interia, pois assim podemos logar o traceback se quisermos.

**Comment by diogommartins** [comment]
Não consegui replicar o problema. único ponto de utilização é  easyqueue.async.AsyncQueue#_handle_message

```python
        except MessageError as e:
            callback = self._handle_callback(self.delegate.on_queue_error,
                                             body=body,
                                             delivery_tag=tag,
                                             error=e,
                                             queue=self)
```
E o que é passado é a Exception

**Comment by diogommartins** [comment]
Isso ainda faz sentido, @daltonmatos  ?

**Comment by daltonmatos** [comment]
Ainda tenho rever, vamos deixar aberto por enquanto.

**Comment by daltonmatos** [comment]
O tempo passou e não revi. Fechando.
