### ISSUE TITLE
Uma instância de AsyncQueue que *não* consome nenhuma fila, precisa de uma implementação de Delegate

### ISSUE THREAD

**Issue by daltonmatos** [B2W-BIT/easyqueue#8]
Mesmo se quisermos ter um código que apenas publica em uma fila, precisamos ter uma implementação minima de um `ConsumerDelegate` (métodos `on_queue_message` e `queue_name`).

Deveria ser possível usar `AsyncQueue` exclusivamente para escrita na fila.

Idealmente poderíamos desvincular o consumer do "producer". 

Faz sentido?

@diogommartins

**Comment by daltonmatos** [comment]
Esse é o erro quando tentamos instanciar um `AsyncQueue` sem passar um `delegate` ou `delegate_class`.

```
Traceback (most recent call last):
  File "__init__.py", line 90, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "__init__.py", line 82, in main
    Queue = AsyncQueue("10.168.200.96", "viniciuslouzada", "4RXzFb6fZ0s1E16o")
  File "/home/vinicius.louzada/.local/share/virtualenvs/cpuWorker-X7epclbV/lib/python3.6/site-packages/easyqueue/async.py", line 28, in init
    raise ValueError("Can't initiate an AsyncQueue withut both "
ValueError: Can't initiate an AsyncQueue withut both delegate and delegate_class
```

**Comment by diogommartins** [comment]
Faz sentido, @daltonmatos . Vou fazer as alterações pra isso
